### ISSUE TITLE
[BUG] Recursive Let Found parsers in flat-map causes CalleeSave re-entry

### ISSUE THREAD

**Issue by DanKirwan** [j-mie6/parsley#241]
## Description

CalleeSave is designed to either be entered or exited, however as this parser can be let found (meaning we don't regenerate the instructions for it), if you recursively call a flatMap from within a flatMap and access the same CalleeSave instance, CalleeSave thinks we're leaving this scope so restores the outside registers which leads to undefined behaviour

## Reproduction Steps
Write this code:
```scala

lazy val x: Parsley[Unit] = death *> 1.makeRef(_=> unit)
lazy val death: Parsley[Unit] = 'x'.flatMap(_ => x)

death.parse("xxx")
``` 

## Expected behavior
This parser should return a failure with unexpected end of input but the scopes of the registers inside should still be consistent
(it's possible to write a recursive state like this that uses the state to end the infinite recursion but this is the simplest example I could find that shows the bug)

## Additional context
**Parsley Version:** 5.0 staging
**Scala Version:** Both 2.13 and 3

**Comment by j-mie6** [comment]
```
>death> (1, 1): xxx•
                ^
  >x> (1, 2): xxx•
               ^
    >death> (1, 2): xxx•
                     ^
    <death< (1, 3): xxx• Good
                      ^
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 8
  at parsley.internal.machine.stacks.ArrayStack.push(ArrayStack.scala:22)
  at parsley.internal.machine.Context.pushAndContinue(Context.scala:234)
  at parsley.internal.machine.instructions.Push.apply(CoreInstrs.scala:18)
  at parsley.internal.machine.Context.go(Context.scala:140)
  at parsley.internal.machine.Context.run(Context.scala:129)
  at parsley.Parsley$.parse$extension(Parsley.scala:133)
  ... 30 elided
```

Interesting trace...

**Comment by j-mie6** [comment]
Ok, so I think this can be fixed by ensuring that `CalleeSave` is re-entrant... I've got that working for the `inUse` flag by pushing it on the stack instead, but the state preservation needs to be converted to use a stack instead of a single array (sadly).

**Comment by DanKirwan** [comment]
I can't remember exactly what I found but for recovery there were loads of problems, I'm pretty sure the only relevant one without recovery is the state stack, I think the approach I used for the state stack was reasonable in the recovery stuff but it did slow down things slightly. 

I'm interested in how you've pushed the inUse onto the stack so it works for knot tying of multiple different let found instances, does it store a reference to the object itself within the pushed inUse flag?

**Comment by j-mie6** [comment]
All I did was `push(false)` as the first instruction of the parser, then before the jump back up at the end a `push(true)`. Basically every time the CalleeSave instruction runs it's either the case that the machine is in a fail state or the top of the stack is a Boolean. Nothing fancy.

**Comment by j-mie6** [comment]
Lol, it's so much worse than we thought: I'm going to have to remove `CalleeSave` and move to a model that just increases the size of the `refs` array on demand (and never reuses an old reference slot.
